In [3]:
import nltk

In [4]:
# !pip install duckduckgo-search
# !pip install -U ddgs#

In [5]:
from ddgs import DDGS 
from collections import defaultdict
import urllib.request
from bs4 import BeautifulSoup

In [6]:
movie = input("Enter movie name:")

In [7]:
t=[]

with DDGS()as ddgs:
    results=ddgs.text(movie + "user review", max_result=5)

In [8]:
for r in results:
    #print(r['href])
    s=r['href']
    t.append(s)
    print(s)

https://www.reddit.com/r/india/comments/u8j7t9/has_anyone_watched_kgf_chapter_2_what_is_your/
https://www.trustpilot.com/
https://www.allmusic.com/album/kgf-mw0004825400
https://m.youtube.com/watch?v=0sSY-hm8IOk
https://www.gadgets360.com/entertainment/kgf-chapter-2-movie-105705
https://www.filmibeat.com/bollywood/movies/kgf-chapter-2-bollywood-movie.html
https://www.youtube.com/shorts/rXw0-vGLxeo
https://www.reddit.com/r/BarefootRunning/comments/zuk6zg/scam_sites_a_list_of_fake_websites/
https://www.amazon.com/RC-Cars-Electric-Rechargeable-Batteries/dp/B0F5HC6ZWP
/clev?event=StartpageResultClick&sc=AR5cSbel8ykKnrdUwOqM1Xbtn6B8yoNKVJYAKrOgJdYn8nVuDWybjjtcspWnXzjIVEQwtGsf26lP12nn3zA3yxRgRfrqWh&payload={"bdsSessionId":"18dc16c2efd24b44b659d7e18f58148e","cheqId":"","countryCode":"IN","deviceType":"mobile","endpoint":"search.serp","hasGoogleAds":false,"page_id":"N6CPykGaCnY1ihpS","queryCategory":"web","segment":"startpage.udog","session_id":"E3tinfApZeRcQ1si","surface":"serp-web","transport":"href-request"}

In [9]:
import re
import pandas as pd

In [10]:
h = []
for i in t:


    try:
        response = urllib.request.urlopen(i)
        html = response.read()
        soup = BeautifulSoup(html)

        text = soup.get_text()
        sentences = re.split(r' *[\.\?!][\' "\)\]]* *', text)
        for t in sentences:
            h.append(t)

    except Exception as e:
        print(e)

df = pd.DataFrame(h, columns = ['Review'])
df

HTTP Error 403: Forbidden
HTTP Error 403: Forbidden
HTTP Error 403: Forbidden
HTTP Error 403: Forbidden
unknown url type: '/clev?event=StartpageResultClick&sc=AR5cSbel8ykKnrdUwOqM1Xbtn6B8yoNKVJYAKrOgJdYn8nVuDWybjjtcspWnXzjIVEQwtGsf26lP12nn3zA3yxRgRfrqWh&payload={"bdsSessionId":"18dc16c2efd24b44b659d7e18f58148e","cheqId":"","countryCode":"IN","deviceType":"mobile","endpoint":"search.serp","hasGoogleAds":false,"page_id":"N6CPykGaCnY1ihpS","queryCategory":"web","segment":"startpage.udog","session_id":"E3tinfApZeRcQ1si","surface":"serp-web","transport":"href-request"}'

                                                Review
0    \n\n\n\n\nReddit - Please wait for verificatio...
1                  KGF - Krishna Godavari Flavours ‚ú®
2     - YouTubeAboutPressCopyrightContact usCreator...
3    \n\n\n\n\nReddit - Please wait for verificatio...
4    \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
..                                                 ...
228  You selected "No, it is not useful"      Chang...
229                   Close to see all product details
230  \n    \n\n  \n \n\n \n\nTop \n\n  \nAbout this...
231                                           com, Inc
232  or its affiliates\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...

[233 rows x 1 columns]

In [11]:
def cleanTxt(text):
    text = re.sub('@[A-Za-z0-9]+', '', text) 
    text = re.sub('#', '', text) 
    text = re.sub('RT[\s]+', '', text) 
    text = re.sub('https?:\/\/\S+', '', text)
    text = re.sub('©', '', text)
    text = re.sub('[0-9]', '', text)
    text = re.sub('%', '', text)  
    return text

In [14]:
df['Review' ]=df['Review'].apply(cleanTxt)

In [17]:
df

                                                Review
0    \n\n\n\n\nReddit - Please wait for verificatio...
1                  KGF - Krishna Godavari Flavours ‚ú®
2     - YouTubeAboutPressCopyrightContact usCreator...
3    \n\n\n\n\nReddit - Please wait for verificatio...
4    \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
..                                                 ...
228  You selected "No, it is not useful"      Chang...
229                   Close to see all product details
230  \n    \n\n  \n \n\n \n\nTop \n\n  \nAbout this...
231                                           com, Inc
232  or its affiliates\n\n\n\n\n\n\n\n\n\n\n\n\n\n\...

[233 rows x 1 columns]

In [18]:
!pip install afinn

Defaulting to user installation because normal site-packages is not writeable
Collecting afinn
  Using cached afinn-0.1-py3-none-any.whl
Installing collected packages: afinn
Successfully installed afinn-0.1

In [ ]:
from afinn import Afinn
positive=[]
negative=[]
neutral=[]

afinn=Afinn()
for review in df['Review']:
    if afinn.score(review)>0:
        positive.append(review)
    elif afinn.score(review)<0:
        negative.append(review)
    elif afinn.score(review)==0:w
        neutral.append(review)

In [20]:
print("Positive Review:", positive)
print('\t\n')
print("\nNegative Review:",negative)
print('\t\n')
print('Neutral Review:',neutral)
print('\t\n')
total_review=len(df['Review'])
print('Total number of review:',total_review)
print("Number of positive review:",len(positive))
print("Number of negative review:",len(negative))
print("Number of neural review:",len(neutral))

Positive Review: ['\n\n\n\n\nReddit - Please wait for verification\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n', '\n\n\n\n\nReddit - Please wait for verification\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n', "us\n\n\n\n\n\n\n\n\n\n\n\n\n\nAll\n\n\nSelect the department you want to search in\n\nAll Departments\nAlbertsons\nAlexa Skills\nAll The Best Pets\nAmazon Devices\nAmazon Fresh\nAmazon Global Store\nAmazon Haul\nAmazon One Medical\nAmazon Pharmacy\nAmazon Resale\nAppliances\nApps & Games\nArts, Crafts & Sewing\nAudible Books & Originals\nAutomotive Parts & Accessories\nBaby\nBartell's\nBashas'\nBeauty & Personal Care\nBooks\nBristol Farms\nCardenas\nCards Supermarket\nCDs & Vinyl\nCell Phones & Accessories\nClothing, Shoes & Jewelry\nWomen's Clothing, Shoes & Jewelry\nMen's Clothing, Shoes & Jewelry\nGirl's Clothing, Shoes & Jewelry\nBoy's Clothing, Shoes & Jewelry\nBaby Clothing, Shoes & Jewelry\nCollectibles & Fine Art\nComputers\nCredit and Payment Cards\ncub\nDigital Music\nElectronics\nFoodMaxx\nFresh Thyme\nGarden & Outdoor\nGift Cards\nGrocery & Gourmet Food\nHandmade\nHealth, Household & Baby Care\nHome & Business Services\nHome & Kitchen\nIndustrial & Scientific\nJust for Prime\nKegNBottle\nKindle Store\nLazy Acres Natural Market\nLucky\nLuggage & Travel Gear\nLuxury Stores\nMagazine Subscriptions\nMetropolitan Market\nMission Wine & Spirits\nMovies & TV\nMusical Instruments\nNew Seasons Market\nOffice Products\nPet Food Express\nPet Supplies\nPetco\nPremium Beauty\nPrime Video\nRite Aid\nSame-Day Store\nSave Mart\nSedano's\nSmart Home\nSoftware\nSousa's Wine & Liquors\nSports & Outdoors\nSubscribe & Save\nSubscription Boxes\nSurdyk's Liquor & Cheese Shop\nTools & Home Improvement\nToys & Games\nUnder $\nVideo Games\nVons\nWeee", "\nWeis\nWhole Foods Market\nWinn Dixie\n\n\n\n\n\n\nSearch Amazon\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nEN\n\n\n\n\n\n\n\nHello\nAccount & Lists\n  \n\n\n\n\nReturns\n& Orders\n\n\n\n\n\n\n\n\n\n\n        Cart\n        \n\n\n\n\n\n\n\n\n\n\n\n\n\nAll\n\n\n\n\n\n\n\n\n\n\n\nHealth AI\n\n\n\n\nMedical Care\n\n\n\n\n\n\nAmazon Basics\n\n\n\n\nWhole Foods\n\n\n\n\nBest Sellers\n\n\n\n\nToday's Deals\n\n\n\n\nNew Releases\n\n\n\n\nBooks\n\n\n\n\nGroceries\n\n\n\n\n\n\nGift Cards\n\n\n\n\n\n\nSell\n\n\n\n\nMusic\n\n\n\n\nRegistry\n\n\n\n\nFashion\n\n\n\n\nAmazon Home\n\n\n\n\nAutomotive\n\n\n\n\nToys & Games\n\n\n\n\nHome Improvement\n\n\n\n\nSports & Outdoors\n\n\n\n\nBaby\n\n\n\n\nSmart Home\n\n\n\n\nShop By Interest\n\n\n\n\nPharmacy\n\n\n\n\nKindle Books\n\n\n\n\nLuxury\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   \n \n\n\n\n\n\n\n \n\n\n\n\n\nToys & Games›Remote & App Controlled Vehicles & Parts›Remote & App Controlled Vehicles›Trucks \n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n \n    \n\n  Prime Member Price    \n\n\n\n\n\n\n\n\n\n\n\n\n\n        \n\n          \n\n\n\n    Ships from:   Amazon       Sold by:   KGF US     \n\n  \n\n\n\n\n\n        \n\n \n\n\n   This price is exclusively for Amazon Prime members", 'Read full return policy     \n\n\n\nPayment \n\n\n  Secure transaction      Your transaction is secure      We work hard to protect your security and privacy', 'We don’t share your credit card details with third-party sellers, and we don’t sell your information to others', "Learn more      \n\n\n\nSupport \n\n\n  Product support included      What's Product Support", "In the event your product doesn't work as expected or you need help using it, Amazon offers free product support options such as live phone/chat with an Amazon associate, manufacturer contact information, step-by-step troubleshooting guides, and help videos", '\n\nBy solving product issues, we help the planet by extending the life of products', 'Availability of support options differ by product and country', 'cardName        ${cardName} not available for the seller you chose     ${cardName} unavailable for quantities greater than ${maxQuantity}', "Read full return policy     \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSupport \n\n\n  Product support included      What's Product Support", "In the event your product doesn't work as expected or you need help using it, Amazon offers free product support options such as live phone/chat with an Amazon associate, manufacturer contact information, step-by-step troubleshooting guides, and help videos", '\n\nBy solving product issues, we help the planet by extending the life of products', 'Availability of support options differ by product and country', 'Learn more      \n\n\n\nGift options \n\n\n\n  \n Available at checkout  \n\n Available at checkout   This item is a gift', 'Change  \n     At checkout, you can add a custom message, a gift receipt for easy returns and have the item gift-wrapped   Add gift options at checkout      \n\n\n\n\n\n\n\n\n\nPayment \n\n\n  Secure transaction      Your transaction is secure      We work hard to protect your security and privacy', 'We don’t share your credit card details with third-party sellers, and we don’t sell your information to others', 'Learn more      \n\n\n\n\n\n  See more    \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n  \n\n\n\n\n\n\n\n  \n\n\n\n\n\n\n\n\n\n\n \n\n     \n\n  Used - Like New   \n\n\n\n\n\n\n\n\n\n\n\n\n  To see product details, add this item to your cart', '\n\n\n\n\n\n        \n FREE Returns  \n  \nReturn this item for free We offer easy, convenient returns with at least one free return option: no shipping charges', 'Learn more about free returns', '\n\n\n\n      \n FREE Returns  \n  \nReturn this item for free We offer easy, convenient returns with at least one free return option: no shipping charges', 'Learn more about free returns', 'cardName        ${cardName} not available for the seller you chose     ${cardName} unavailable for quantities greater than ${maxQuantity}', '\n\n  Sold by Amazon Resale and Fulfilled by Amazon', 'Please try again', 'Please try again', '\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n    \n FREE Returns  \n  \nReturn this item for free We offer easy, convenient returns with at least one free return option: no shipping charges', 'Learn more about free returns', '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n \n Save     on  select item(s)     Terms      \n\n Save     on  select item(s)     Terms      \n\n\n\n \n \n Save     on  select item(s)     Terms      \n\n Save     on  select item(s)     Terms      \n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n To see product details, add this item to your cart', '\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n    \n FREE Returns  \n  \nReturn this item for free We offer easy, convenient returns with at least one free return option: no shipping charges', 'Learn more about free returns', '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n \n Save     on  select item(s)     Terms      \n\n Save     on  select item(s)     Terms      \n\n\n\n \n \n Save     on  select item(s)     Terms      \n\n Save     on  select item(s)     Terms      \n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n To see product details, add this item to your cart', '\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n    \n FREE Returns  \n  \nReturn this item for free We offer easy, convenient returns with at least one free return option: no shipping charges', 'Learn more about free returns', '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n \n Save     on  select item(s)     Terms      \n\n Save     on  select item(s)     Terms      \n\n\n\n \n \n Save     on  select item(s)     Terms      \n\n Save     on  select item(s)     Terms      \n\n\n\n\n\n \n\n\n\n \n\n \n\n\n\n\n\n     Available at a lower price from other sellers that may not offer free Prime shipping', '\n\n\n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSign in to continue\n\n\n\n \n\n \n\n\n\n\n\n\n\n\n\n\n\n\n\n   【 New Upgraded Version: Boosted Safety & Reliability】This fast rc cars circuit board adds waterproof glue for better protection, both motor and circuit board are equipped with heatsinks to prevent overheating', "The battery of the remote control car comes with a battery management system that prevents overcharging, over-discharging and short circuits,which is more secure,it's the ideal choice among hobby RC cars", '【Upgraded Safety System & Reliable Battery Protectiony】Equipped with a built-in BMS battery system to prevent overcharge, over-discharge, and short circuits', 'Please use and store in open, ventilated areas to ensure safe operation', '【Full Metal Durable Structure & All-Terrain Design】Full metal drive shaft, metal shock absorbers, and stable differential system for reliable high-speed performance', '【Powerful RC Motor & Stable KM/H High Speed】Powered by a high-torque  brushed motor with smooth and responsive control', 'The efficient transmission structure ensures stable speed and low heat generation', 'Allow – minutes of cooling after – minutes of continuous use', 'V safe Li-Po batteries and a certified charger', 'Each battery supports  minutes of play for a total of up to  minutes', '【 Standard & Drift Dual Tire Modes with Safe Operation】Includes high-grip off-road tires and extra drift tires for racing and drifting fun', 'GHz anti-interference system supports stable control', 'This RC car is suitable for kids and adults with complete safety instructions', '【Durable PVC Body & Sleek Functional Design】Our RC monster truck has a flexible, solid PVC body—impact/scratch-resistant, protecting internal components', 'Its sleek, streamlined design (tailored for big rc cars) enhances aerodynamics, boosting speed/maneuverability for smoother racing', 'It blends durability, top-tier performance, hassle-free fun', 'Join KGF’s stunning RC world', '\n   【Vibrant LED Lights: Cool Visuals for Day & Night Racing】The radio controlled car comes with bright headlights that shine dazzlingly in the dark', 'Whether racing during the day for eye-catching style or pulling off epic stunts at night, the LED lights boost visibility and deliver an awesome visual experience', 'They add a fun, dynamic flair to every drive, making your racing moments more exciting—this rc trucks perfect for kids and hobbyists chasing cool, immersive play', 'GHz Intelligent Remote Control】This off-road fast RC car features a ', 'GHz proportional radio system with ft stable range, perfect for long-distance racing', 'The ergonomic remote fits comfortably, offering real-car-like speed/steering control—ideal for kids and beginners', 'Enjoy lightning-fast response (forward/brake/reverse) even during high-speed rallies or drifting', 'With adjustable TRIM/SPEED, each car-remote pair is interference-free, ensuring non-stop racing fun for the whole family', '【Ideal Gift for Kids & Adults】The high-speed remote control car is an ideal gift for birthdays, holidays,Christmas gift', 'Small rc car size is just right and easy to carry, it’s novice-friendly and accessible—great for remote control car for boys -, rc cars for boys age -', 'The hobby rc car becomes a fantastic companion for family/friend outings, camping, or casual races', 'Share the joy of driving, unleash stress, and create memorable fun—this is the gift they’ll love and remember', 'GHz Electric Toy Vehicle Gift for Teens and + (: Scale)Next set of slides\n\n\n\n \n\n\n \n\n\n\n\n\n\n\n\n \n\n\nFrom the brand \n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n     \n\n\n \n\n KGF : RC Cars - Smarter, Tougher, Faster', 'Reinforced components & fine-tuned chassis conquer all terrain', 'This rugged build laughs at crashes while delivering heart-pounding KGF speed', 'More responsive, more resilient - pure adrenaline', 'Keep Games Funny', '          Manufacturer Part Number        K          Manufacturer        KGF       Best Sellers Rank     , in Toys & Games (See Top  in Toys & Games)  in Hobby RC Trucks          ASIN        BFHCZWP            Additional details           Material Type        Plastic            \n  Warranty & Support    Amazon', 'com Voluntary -Day Return Guarantee: You can return many items you have purchased within  days following delivery of the item to you', 'Product Warranty: For warranty information about this product, please click here   \n   Feedback                                                   \n\n\n Would you like to  \n tell us about a lower price', 'GHz KPH High Speed Remote Control Car, WD Off Road Monster Truck X Fast Drift Wheel RC Truck with  Rechargeable Batteries\n\nShare:\n                                    \n\n\n\n\n\n\nFound a lower price', "Although we can't match every price reported, we'll use your feedback to ensure that our prices remain competitive", '\nFields with an asterisk * are required\n\n\nPrice Availability\n\n\n\n\nWebsite (Online)\n\n\n\n\nURL *:\n\n\n\n\n\n\n\n\n\n\n\nPrice\n                                        ($)\n                                        *:\n                                    \n\n\n\n\n\n\n\n\n\n\n\nShipping cost\n                                        ($):\n                                    \n\n\n\n\n\n\n\n\n\n\n\n\n Date of the price\n                                        (MM/DD/YYYY):\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    /\n                                                \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    /\n                                                \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nStore (Offline)\n\n\n\n\n\n                                            Store name *:\n                                    \n\n\n\n                                                Enter the store name where you found this product\n                                            \n\n\n\n\n\n                        Enter the store name where you found this product\n                    \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                            City *:\n\n\n\n\n\n\n\n\n\n\n\n                                            State:\n                                    \n\n\n\n                                                                    Please select province \n\n\n\n\nPlease select province \n\n\n\n\n\n\n\nPrice\n                                        ($)\n                                        *:\n                                    \n\n\n\n\n\n\n\n\n\n\n\n\nDate of the price\n                                        (MM/DD/YYYY):\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    /\n                                                \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    /\n                                                \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSubmit Feedback\n\n\n\n\n\n\n\n\n\n\n                        Please sign in to provide feedback', '\n\n \n                Features & Specs           Power Source        Battery Powered          Additional Features        Convertible, Portable, Rechargeable          Operation Mode        Remote Control          Battery Description        Lithium-Ion Polymer          Are Batteries Required        Yes          Number of Batteries         Lithium Polymer batteries required', "\n\n\n\n\nSafety and product resourcesSafety documentsUser Manual (PDF)\n\n\n\n \n\n\n\n\n   What's in the box    Remote   Battery   \n\n\n\n\n\n\n\n\n\n  Important information  Safety Information CHOKING HAZARD - Small parts", 'Not suitable for children under  years', 'Allow - minutes cool-down after  minutes of continuous running', 'To switch between racing and drifting tires, remove the existing tires and replace them with the desired set', "For night racing, use the car's LED lights for better visibility", '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSimilar brands on AmazonPage  of Start OverSponsoredPrevious pageShop the Store on Amazon ›Zalneo Remote Control Car – WD ° Flip Double‑Sided RC Stunt Car LED Light Bar & USB‑C Modular Battery, Off‑Road Toys for Boys Ages\u202f‑, Birthday Gift, Black‑GreenShop the Store on Amazon ›MOCOMI RC Drift Car : Scale, WD Remote Control Car with LED Lights KM/H High Speed, Dual-Mode Racing & Drifting Toy Car with  Batteries, Gift for Kids & Adults, SilverShop the Store on Amazon ›HOMETALL : Fast RC Cars for Adults - + KPH Off Road Remote Control Car - High Speed RC Monster Truck x All Terrain offLimited time dealShop the Store on Amazon ›BEZGAR : Monster Truck Toys, °Stunt RC Cars Rotation Dinosaur Toys with Music,  Batteries and Wireless LED Strobe Lights, Remote Control Car for Boys       Years Old(Green) offLimited time dealShop the Store on Amazon ›VIDUTC Waterproof Monster Truck Remote Control Car, : Bigger Amphibious RC Cars Toys, Long Battery WD All Terrain Off-Road Vehicle for       + Boys Girls Kids Ideal BirthdayNext page\n\n\n\n \n\n\n\n\n\n\n \n\n\n \n\n\n\n\n\n\n     Product summary presents key product information       Keyboard shortcut\xa0 \nshift\n+\nalt\n+\nopt\n+\nD\n\n     \n\n\n    Product Summary: KGF : Scale All Terrain RC Cars for Adults, ', 'GHz KPH High Speed Remote Control Car, WD Off Road Monster Truck X Fast Drift Wheel RC Truck with  Rechargeable Batteries  From KGF   Price   No featured offers available     Other sellers       Other sellers      About this Item  【 New Upgraded Version: Boosted Safety & Reliability】This fast rc cars circuit board adds waterproof glue for better protection, both motor and circuit board are equipped with heatsinks to prevent overheating', "The battery of the remote control car comes with a battery management system that prevents overcharging, over-discharging and short circuits,which is more secure,it's the ideal choice among hobby RC cars", '【Upgraded Safety System & Reliable Battery Protectiony】Equipped with a built-in BMS battery system to prevent overcharge, over-discharge, and short circuits', 'Please use and store in open, ventilated areas to ensure safe operation', '【Full Metal Durable Structure & All-Terrain Design】Full metal drive shaft, metal shock absorbers, and stable differential system for reliable high-speed performance', '【Powerful RC Motor & Stable KM/H High Speed】Powered by a high-torque  brushed motor with smooth and responsive control', 'The efficient transmission structure ensures stable speed and low heat generation', 'Allow – minutes of cooling after – minutes of continuous use', 'V safe Li-Po batteries and a certified charger', 'Each battery supports  minutes of play for a total of up to  minutes', '【 Standard & Drift Dual Tire Modes with Safe Operation】Includes high-grip off-road tires and extra drift tires for racing and drifting fun', 'GHz anti-interference system supports stable control', 'This RC car is suitable for kids and adults with complete safety instructions', '【Durable PVC Body & Sleek Functional Design】Our RC monster truck has a flexible, solid PVC body—impact/scratch-resistant, protecting internal components', 'Its sleek, streamlined design (tailored for big rc cars) enhances aerodynamics, boosting speed/maneuverability for smoother racing', 'It blends durability, top-tier performance, hassle-free fun', 'Join KGF’s stunning RC world', '【Vibrant LED Lights: Cool Visuals for Day & Night Racing】The radio controlled car comes with bright head